FROM python:3.12-slim

WORKDIR /app

RUN pip install fastapi uvicorn torch transformers --no-cache-dir

COPY server.py .
RUN mkdir -p utils
COPY ../utils/model.py ./utils/model.py

CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]